sudo: false
language: python
cache: pip
services:
  - redis-server
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
  - "nightly"
install: travis_retry pip install tox-travis
script:
- tox

